name: "Test"
on:
  push:

jobs:
  check-rgd:
    runs-on: ubuntu-latest
    steps:
      - uses: marcoroth/dependabot-bump-together-action@update_all_deps
        with:
          dependencies: django-rgd
          update_all: true
          package_managers: pip
          directory: /
          branch: main
          username: x-access-token
          token: ${{ secrets.GITHUB_TOKEN }}
