name: "Test"
on:
  pull_request:
    types: [opened, reopened]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ github.ref }}
    - run: echo ${{ github.event.pull_request.head.ref }}
    - run: echo ${{ startsWith(github.ref, 'refs/heads/maint') }}
    - if: startsWith(github.event.pull_request.head.ref, 'maint')
      run: echo "got it"

    # - uses: actions-ecosystem/action-add-labels@v1
    #   if: startsWith(github.ref, 'refs/heads/maint') || startsWith(github.ref, 'refs/heads/no-ci') || startsWith(github.ref, 'refs/heads/ci')
    #   with:
    #     labels: maintenance
    # - uses: actions-ecosystem/action-add-labels@v1
    #   if: startsWith(github.ref, 'refs/heads/junk')
    #   with:
    #     labels: ignore-for-release
    # - uses: actions-ecosystem/action-add-labels@v1
    #   if: startsWith(github.ref, 'refs/heads/feat')
    #   with:
    #     labels: enhancement
    #
    # - uses: actions-ecosystem/action-add-labels@v1
    #   if: startsWith(github.ref, 'refs/heads/fix') || startsWith(github.ref, 'refs/heads/patch')
    #   with:
    #     labels: bug-fix
