name: "Pull Request Labeler"
on:
  pull_request_target:
    types: [opened, reopened]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.pull_request.head.ref }}"

      # Label based on branch name
      - if: startsWith(github.event.pull_request.head.ref, 'doc/') || startsWith(github.event.pull_request.head.ref, 'docs')
        run: echo "got it"

      - uses: actions-ecosystem/action-add-labels@v1
        if: startsWith(github.event.pull_request.head.ref, 'doc/') || startsWith(github.event.pull_request.head.ref, 'docs')
        with:
          labels: documentation
          github_token: ${{ secrets.GITHUB_TOKEN }}
