on: 
  workflow_call:
  push:
    branches:
      - main
  pull_request:
name: Slack Notification Demo
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      #if: failure()
      env:
        SLACK_CHANNEL: tmp-bane-ghactions-notify
        SLACK_COLOR: '#db540b'
        SLACK_LINK_NAMES: true
        SLACK_MESSAGE: "@Bane, Notification from GitHub Actions"
        SLACK_TITLE: "Test Actions"
        SLACK_FOOTER: "This is a footer message"
        SLACK_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
